---
- name: gems | gem home directory exists
  file:
    path: "{{ gems_dir }}"
    state: directory

- name: gems | project gems installed
  gem:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    user_install: no
  with_items:
    - { name: "sinatra", version: "1.3.2" }
    - { name: "sinatra-contrib", version: "1.3.2" }
    - { name: "rdiscount", version: "2.0.7.1" }
  environment:
    GEM_HOME: "{{ gems_dir }}"
