---
- hosts: all
  remote_user: "{{ root_user }}"
  gather_facts: False
  roles:
    - role: common

- hosts: all
  remote_user: "{{ root_user }}"
  roles:
    - role: common.remote
      tags:
        -  remote

- hosts: all
  remote_user: "{{ user }}"
  roles:
    - role: common
    - role: ruby
    - role: webserver
      static: False

- import_playbook: deploy.yml
